//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Bart.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Bart.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident conference bridge.
        /// </summary>
        public static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t log you in. Please try again later..
        /// </summary>
        public static string CantLogIn {
            get {
                return ResourceManager.GetString("CantLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the incident.
        /// </summary>
        public static string CloseIncidentTextCarousel {
            get {
                return ResourceManager.GetString("CloseIncidentTextCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize **{command}** as valid command. Please type &apos;Help&apos; to see all available commands..
        /// </summary>
        public static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Incident.
        /// </summary>
        public static string CreateIncident {
            get {
                return ResourceManager.GetString("CreateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit workstream.
        /// </summary>
        public static string EditWorkstream {
            get {
                return ResourceManager.GetString("EditWorkstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string ExceptionResponse {
            get {
                return ResourceManager.GetString("ExceptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized to access this bot. Please contact your administrator for help..
        /// </summary>
        public static string InvalidTenant {
            get {
                return ResourceManager.GetString("InvalidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in successfully!.
        /// </summary>
        public static string LoggedInSuccess {
            get {
                return ResourceManager.GetString("LoggedInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an incident
        ///.
        /// </summary>
        public static string ReportIncidentHeaderCarousel {
            get {
                return ResourceManager.GetString("ReportIncidentHeaderCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not signed in to perform this action. Please type &apos;Sign in&apos; to proceed..
        /// </summary>
        public static string SignInErrorMessage {
            get {
                return ResourceManager.GetString("SignInErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in required.
        /// </summary>
        public static string SignInRequired {
            get {
                return ResourceManager.GetString("SignInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only support below commands..
        /// </summary>
        public static string SupportedCommands {
            get {
                return ResourceManager.GetString("SupportedCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Tour.
        /// </summary>
        public static string TakeTour {
            get {
                return ResourceManager.GetString("TakeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update workstream.
        /// </summary>
        public static string UpdateWorkstreamHeaderCarousel {
            get {
                return ResourceManager.GetString("UpdateWorkstreamHeaderCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create, view and add people in workstream.
        /// </summary>
        public static string UpdateWorkstreamTextCarousel {
            get {
                return ResourceManager.GetString("UpdateWorkstreamTextCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View incidents.
        /// </summary>
        public static string ViewIncidents {
            get {
                return ResourceManager.GetString("ViewIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View workstreams.
        /// </summary>
        public static string ViewWorkstreams {
            get {
                return ResourceManager.GetString("ViewWorkstreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am on call assistant BOT that can help create, manage and resolve incidents..
        /// </summary>
        public static string WelcomeCardTextLine1 {
            get {
                return ResourceManager.GetString("WelcomeCardTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what i can help with,.
        /// </summary>
        public static string WelcomeCardTextLine2 {
            get {
                return ResourceManager.GetString("WelcomeCardTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new incident.
        /// </summary>
        public static string WelcomeCardTextLine3 {
            get {
                return ResourceManager.GetString("WelcomeCardTextLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, Edit and assign workstreams.
        /// </summary>
        public static string WelcomeCardTextLine4 {
            get {
                return ResourceManager.GetString("WelcomeCardTextLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve or close incidents.
        /// </summary>
        public static string WelcomeCardTextLine5 {
            get {
                return ResourceManager.GetString("WelcomeCardTextLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
